service: aws-node-alexa-skill

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  luckyNumber:
    handler: index.handler
    events:
      - alexaSkill
